# This is a basic workflow to help you get started with Actions
name: CI/CD
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build job
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Use Node.js 16.13
        uses: actions/setup-node@v1
        with:
          node-version: 16.13
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm install
      # Runs a set of commands to build
      - name: Build
        run: npm run build -- --prod
  # deploy job   
  deploy:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    # only run if build job complte successfully 
    needs: [build]
    steps:
      # building the app before deploy
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13
      # Install the dependencies need to build the app
      - name: Install Dependencies
        run: npm install
      # build the app
      - name: Build the app artifact for prod
        run: npm run build -- --prod
      # ddeploy the app artifact to firebase
      - name: Deploy angular app to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
